/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:59b902d2-18b9-42f0-907d-b38b1c61b821",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9LV04ZzyG",
    "aws_user_pools_web_client_id": "2292ddjf5rkbnaohau3lkudmj7",
    "oauth": {
        "domain": "tabledealsc698e540-c698e540-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://tabledeals-mvp.herokuapp.com/,https://table-deals.herokuapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://tabledeals-mvp.herokuapp.com/,https://table-deals.herokuapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
